/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IReactiveOrchestrator {
  export type ExecutionLogStruct = {
    ruleId: BigNumberish;
    timestamp: BigNumberish;
    success: boolean;
    returnData: BytesLike;
    gasUsed: BigNumberish;
  };

  export type ExecutionLogStructOutput = [
    ruleId: bigint,
    timestamp: bigint,
    success: boolean,
    returnData: string,
    gasUsed: bigint
  ] & {
    ruleId: bigint;
    timestamp: bigint;
    success: boolean;
    returnData: string;
    gasUsed: bigint;
  };

  export type RuleStruct = {
    source: AddressLike;
    eventSig: BytesLike;
    threshold: BigNumberish;
    target: AddressLike;
    callData: BytesLike;
    active: boolean;
    createdAt: BigNumberish;
  };

  export type RuleStructOutput = [
    source: string,
    eventSig: string,
    threshold: bigint,
    target: string,
    callData: string,
    active: boolean,
    createdAt: bigint
  ] & {
    source: string;
    eventSig: string;
    threshold: bigint;
    target: string;
    callData: string;
    active: boolean;
    createdAt: bigint;
  };
}

export interface ReactiveOrchestratorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateRule"
      | "executeTargetCall"
      | "getExecutionLogs"
      | "getNextRuleId"
      | "getRule"
      | "isRuleActive"
      | "onEvent"
      | "owner"
      | "registerRule"
      | "supportsInterface"
      | "testTriggerEvent"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "DebugCalled"
      | "RuleDeactivated"
      | "RuleExecuted"
      | "RuleFailed"
      | "RuleRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateRule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "executeTargetCall",
    values: [AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutionLogs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getNextRuleId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getRule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRuleActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "onEvent",
    values: [AddressLike, BytesLike[], BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "registerRule",
    values: [AddressLike, BytesLike, BigNumberish, AddressLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "testTriggerEvent",
    values: [AddressLike, BytesLike[], BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "executeTargetCall",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutionLogs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getNextRuleId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRuleActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "onEvent", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "testTriggerEvent",
    data: BytesLike
  ): Result;
}

export namespace DebugCalledEvent {
  export type InputTuple = [
    caller: AddressLike,
    emitter: AddressLike,
    topicsLen: BigNumberish,
    gasLeft: BigNumberish
  ];
  export type OutputTuple = [
    caller: string,
    emitter: string,
    topicsLen: bigint,
    gasLeft: bigint
  ];
  export interface OutputObject {
    caller: string;
    emitter: string;
    topicsLen: bigint;
    gasLeft: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RuleDeactivatedEvent {
  export type InputTuple = [ruleId: BigNumberish];
  export type OutputTuple = [ruleId: bigint];
  export interface OutputObject {
    ruleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RuleExecutedEvent {
  export type InputTuple = [
    ruleId: BigNumberish,
    success: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    ruleId: bigint,
    success: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    ruleId: bigint;
    success: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RuleFailedEvent {
  export type InputTuple = [ruleId: BigNumberish, reason: BytesLike];
  export type OutputTuple = [ruleId: bigint, reason: string];
  export interface OutputObject {
    ruleId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RuleRegisteredEvent {
  export type InputTuple = [
    ruleId: BigNumberish,
    source: AddressLike,
    target: AddressLike
  ];
  export type OutputTuple = [ruleId: bigint, source: string, target: string];
  export interface OutputObject {
    ruleId: bigint;
    source: string;
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReactiveOrchestrator extends BaseContract {
  connect(runner?: ContractRunner | null): ReactiveOrchestrator;
  waitForDeployment(): Promise<this>;

  interface: ReactiveOrchestratorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateRule: TypedContractMethod<
    [ruleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  executeTargetCall: TypedContractMethod<
    [target: AddressLike, callData: BytesLike],
    [[boolean, string] & { success: boolean; returnData: string }],
    "nonpayable"
  >;

  getExecutionLogs: TypedContractMethod<
    [ruleId: BigNumberish],
    [IReactiveOrchestrator.ExecutionLogStructOutput[]],
    "view"
  >;

  getNextRuleId: TypedContractMethod<[], [bigint], "view">;

  getRule: TypedContractMethod<
    [ruleId: BigNumberish],
    [IReactiveOrchestrator.RuleStructOutput],
    "view"
  >;

  isRuleActive: TypedContractMethod<[ruleId: BigNumberish], [boolean], "view">;

  onEvent: TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  registerRule: TypedContractMethod<
    [
      source: AddressLike,
      eventSig: BytesLike,
      threshold: BigNumberish,
      target: AddressLike,
      callData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  testTriggerEvent: TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateRule"
  ): TypedContractMethod<[ruleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "executeTargetCall"
  ): TypedContractMethod<
    [target: AddressLike, callData: BytesLike],
    [[boolean, string] & { success: boolean; returnData: string }],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getExecutionLogs"
  ): TypedContractMethod<
    [ruleId: BigNumberish],
    [IReactiveOrchestrator.ExecutionLogStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getNextRuleId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getRule"
  ): TypedContractMethod<
    [ruleId: BigNumberish],
    [IReactiveOrchestrator.RuleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRuleActive"
  ): TypedContractMethod<[ruleId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "onEvent"
  ): TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerRule"
  ): TypedContractMethod<
    [
      source: AddressLike,
      eventSig: BytesLike,
      threshold: BigNumberish,
      target: AddressLike,
      callData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "testTriggerEvent"
  ): TypedContractMethod<
    [emitter: AddressLike, eventTopics: BytesLike[], data: BytesLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "DebugCalled"
  ): TypedContractEvent<
    DebugCalledEvent.InputTuple,
    DebugCalledEvent.OutputTuple,
    DebugCalledEvent.OutputObject
  >;
  getEvent(
    key: "RuleDeactivated"
  ): TypedContractEvent<
    RuleDeactivatedEvent.InputTuple,
    RuleDeactivatedEvent.OutputTuple,
    RuleDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "RuleExecuted"
  ): TypedContractEvent<
    RuleExecutedEvent.InputTuple,
    RuleExecutedEvent.OutputTuple,
    RuleExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RuleFailed"
  ): TypedContractEvent<
    RuleFailedEvent.InputTuple,
    RuleFailedEvent.OutputTuple,
    RuleFailedEvent.OutputObject
  >;
  getEvent(
    key: "RuleRegistered"
  ): TypedContractEvent<
    RuleRegisteredEvent.InputTuple,
    RuleRegisteredEvent.OutputTuple,
    RuleRegisteredEvent.OutputObject
  >;

  filters: {
    "DebugCalled(address,address,uint256,uint256)": TypedContractEvent<
      DebugCalledEvent.InputTuple,
      DebugCalledEvent.OutputTuple,
      DebugCalledEvent.OutputObject
    >;
    DebugCalled: TypedContractEvent<
      DebugCalledEvent.InputTuple,
      DebugCalledEvent.OutputTuple,
      DebugCalledEvent.OutputObject
    >;

    "RuleDeactivated(uint256)": TypedContractEvent<
      RuleDeactivatedEvent.InputTuple,
      RuleDeactivatedEvent.OutputTuple,
      RuleDeactivatedEvent.OutputObject
    >;
    RuleDeactivated: TypedContractEvent<
      RuleDeactivatedEvent.InputTuple,
      RuleDeactivatedEvent.OutputTuple,
      RuleDeactivatedEvent.OutputObject
    >;

    "RuleExecuted(uint256,bool,uint256)": TypedContractEvent<
      RuleExecutedEvent.InputTuple,
      RuleExecutedEvent.OutputTuple,
      RuleExecutedEvent.OutputObject
    >;
    RuleExecuted: TypedContractEvent<
      RuleExecutedEvent.InputTuple,
      RuleExecutedEvent.OutputTuple,
      RuleExecutedEvent.OutputObject
    >;

    "RuleFailed(uint256,bytes)": TypedContractEvent<
      RuleFailedEvent.InputTuple,
      RuleFailedEvent.OutputTuple,
      RuleFailedEvent.OutputObject
    >;
    RuleFailed: TypedContractEvent<
      RuleFailedEvent.InputTuple,
      RuleFailedEvent.OutputTuple,
      RuleFailedEvent.OutputObject
    >;

    "RuleRegistered(uint256,address,address)": TypedContractEvent<
      RuleRegisteredEvent.InputTuple,
      RuleRegisteredEvent.OutputTuple,
      RuleRegisteredEvent.OutputObject
    >;
    RuleRegistered: TypedContractEvent<
      RuleRegisteredEvent.InputTuple,
      RuleRegisteredEvent.OutputTuple,
      RuleRegisteredEvent.OutputObject
    >;
  };
}
