/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace IReactiveOrchestrator {
  export type ExecutionLogStruct = {
    ruleId: BigNumberish;
    timestamp: BigNumberish;
    success: boolean;
    returnData: BytesLike;
    gasUsed: BigNumberish;
  };

  export type ExecutionLogStructOutput = [
    ruleId: bigint,
    timestamp: bigint,
    success: boolean,
    returnData: string,
    gasUsed: bigint
  ] & {
    ruleId: bigint;
    timestamp: bigint;
    success: boolean;
    returnData: string;
    gasUsed: bigint;
  };

  export type RuleStruct = {
    source: AddressLike;
    eventSig: BytesLike;
    threshold: BigNumberish;
    target: AddressLike;
    callData: BytesLike;
    active: boolean;
    createdAt: BigNumberish;
  };

  export type RuleStructOutput = [
    source: string,
    eventSig: string,
    threshold: bigint,
    target: string,
    callData: string,
    active: boolean,
    createdAt: bigint
  ] & {
    source: string;
    eventSig: string;
    threshold: bigint;
    target: string;
    callData: string;
    active: boolean;
    createdAt: bigint;
  };
}

export interface IReactiveOrchestratorInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "deactivateRule"
      | "getExecutionLogs"
      | "getRule"
      | "isRuleActive"
      | "registerRule"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "RuleDeactivated"
      | "RuleExecuted"
      | "RuleFailed"
      | "RuleRegistered"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "deactivateRule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getExecutionLogs",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRule",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isRuleActive",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "registerRule",
    values: [AddressLike, BytesLike, BigNumberish, AddressLike, BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "deactivateRule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getExecutionLogs",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getRule", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isRuleActive",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerRule",
    data: BytesLike
  ): Result;
}

export namespace RuleDeactivatedEvent {
  export type InputTuple = [ruleId: BigNumberish];
  export type OutputTuple = [ruleId: bigint];
  export interface OutputObject {
    ruleId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RuleExecutedEvent {
  export type InputTuple = [
    ruleId: BigNumberish,
    success: boolean,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [
    ruleId: bigint,
    success: boolean,
    timestamp: bigint
  ];
  export interface OutputObject {
    ruleId: bigint;
    success: boolean;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RuleFailedEvent {
  export type InputTuple = [ruleId: BigNumberish, reason: BytesLike];
  export type OutputTuple = [ruleId: bigint, reason: string];
  export interface OutputObject {
    ruleId: bigint;
    reason: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RuleRegisteredEvent {
  export type InputTuple = [
    ruleId: BigNumberish,
    source: AddressLike,
    target: AddressLike
  ];
  export type OutputTuple = [ruleId: bigint, source: string, target: string];
  export interface OutputObject {
    ruleId: bigint;
    source: string;
    target: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IReactiveOrchestrator extends BaseContract {
  connect(runner?: ContractRunner | null): IReactiveOrchestrator;
  waitForDeployment(): Promise<this>;

  interface: IReactiveOrchestratorInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  deactivateRule: TypedContractMethod<
    [ruleId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getExecutionLogs: TypedContractMethod<
    [ruleId: BigNumberish],
    [IReactiveOrchestrator.ExecutionLogStructOutput[]],
    "view"
  >;

  getRule: TypedContractMethod<
    [ruleId: BigNumberish],
    [IReactiveOrchestrator.RuleStructOutput],
    "view"
  >;

  isRuleActive: TypedContractMethod<[ruleId: BigNumberish], [boolean], "view">;

  registerRule: TypedContractMethod<
    [
      source: AddressLike,
      eventSig: BytesLike,
      threshold: BigNumberish,
      target: AddressLike,
      callData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "deactivateRule"
  ): TypedContractMethod<[ruleId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getExecutionLogs"
  ): TypedContractMethod<
    [ruleId: BigNumberish],
    [IReactiveOrchestrator.ExecutionLogStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getRule"
  ): TypedContractMethod<
    [ruleId: BigNumberish],
    [IReactiveOrchestrator.RuleStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "isRuleActive"
  ): TypedContractMethod<[ruleId: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "registerRule"
  ): TypedContractMethod<
    [
      source: AddressLike,
      eventSig: BytesLike,
      threshold: BigNumberish,
      target: AddressLike,
      callData: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  getEvent(
    key: "RuleDeactivated"
  ): TypedContractEvent<
    RuleDeactivatedEvent.InputTuple,
    RuleDeactivatedEvent.OutputTuple,
    RuleDeactivatedEvent.OutputObject
  >;
  getEvent(
    key: "RuleExecuted"
  ): TypedContractEvent<
    RuleExecutedEvent.InputTuple,
    RuleExecutedEvent.OutputTuple,
    RuleExecutedEvent.OutputObject
  >;
  getEvent(
    key: "RuleFailed"
  ): TypedContractEvent<
    RuleFailedEvent.InputTuple,
    RuleFailedEvent.OutputTuple,
    RuleFailedEvent.OutputObject
  >;
  getEvent(
    key: "RuleRegistered"
  ): TypedContractEvent<
    RuleRegisteredEvent.InputTuple,
    RuleRegisteredEvent.OutputTuple,
    RuleRegisteredEvent.OutputObject
  >;

  filters: {
    "RuleDeactivated(uint256)": TypedContractEvent<
      RuleDeactivatedEvent.InputTuple,
      RuleDeactivatedEvent.OutputTuple,
      RuleDeactivatedEvent.OutputObject
    >;
    RuleDeactivated: TypedContractEvent<
      RuleDeactivatedEvent.InputTuple,
      RuleDeactivatedEvent.OutputTuple,
      RuleDeactivatedEvent.OutputObject
    >;

    "RuleExecuted(uint256,bool,uint256)": TypedContractEvent<
      RuleExecutedEvent.InputTuple,
      RuleExecutedEvent.OutputTuple,
      RuleExecutedEvent.OutputObject
    >;
    RuleExecuted: TypedContractEvent<
      RuleExecutedEvent.InputTuple,
      RuleExecutedEvent.OutputTuple,
      RuleExecutedEvent.OutputObject
    >;

    "RuleFailed(uint256,bytes)": TypedContractEvent<
      RuleFailedEvent.InputTuple,
      RuleFailedEvent.OutputTuple,
      RuleFailedEvent.OutputObject
    >;
    RuleFailed: TypedContractEvent<
      RuleFailedEvent.InputTuple,
      RuleFailedEvent.OutputTuple,
      RuleFailedEvent.OutputObject
    >;

    "RuleRegistered(uint256,address,address)": TypedContractEvent<
      RuleRegisteredEvent.InputTuple,
      RuleRegisteredEvent.OutputTuple,
      RuleRegisteredEvent.OutputObject
    >;
    RuleRegistered: TypedContractEvent<
      RuleRegisteredEvent.InputTuple,
      RuleRegisteredEvent.OutputTuple,
      RuleRegisteredEvent.OutputObject
    >;
  };
}
