/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface LiquidityPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getAPY"
      | "getLiquidity"
      | "getPrice"
      | "owner"
      | "updateAPY"
      | "updateLiquidity"
      | "updatePrice"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "APYUpdated"
      | "LiquidityUpdated"
      | "OraclePriceUpdated"
      | "ThresholdCrossed"
  ): EventFragment;

  encodeFunctionData(functionFragment: "getAPY", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getLiquidity",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getPrice", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "updateAPY",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updatePrice",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "getAPY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "updateAPY", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "updateLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updatePrice",
    data: BytesLike
  ): Result;
}

export namespace APYUpdatedEvent {
  export type InputTuple = [newAPY: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [newAPY: bigint, timestamp: bigint];
  export interface OutputObject {
    newAPY: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidityUpdatedEvent {
  export type InputTuple = [
    newLiquidity: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [newLiquidity: bigint, timestamp: bigint];
  export interface OutputObject {
    newLiquidity: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OraclePriceUpdatedEvent {
  export type InputTuple = [newPrice: BigNumberish, timestamp: BigNumberish];
  export type OutputTuple = [newPrice: bigint, timestamp: bigint];
  export interface OutputObject {
    newPrice: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ThresholdCrossedEvent {
  export type InputTuple = [
    metric: string,
    value: BigNumberish,
    threshold: BigNumberish
  ];
  export type OutputTuple = [metric: string, value: bigint, threshold: bigint];
  export interface OutputObject {
    metric: string;
    value: bigint;
    threshold: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface LiquidityPool extends BaseContract {
  connect(runner?: ContractRunner | null): LiquidityPool;
  waitForDeployment(): Promise<this>;

  interface: LiquidityPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getAPY: TypedContractMethod<[], [bigint], "view">;

  getLiquidity: TypedContractMethod<[], [bigint], "view">;

  getPrice: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  updateAPY: TypedContractMethod<[newAPY: BigNumberish], [void], "nonpayable">;

  updateLiquidity: TypedContractMethod<
    [newLiquidity: BigNumberish],
    [void],
    "nonpayable"
  >;

  updatePrice: TypedContractMethod<
    [newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getAPY"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLiquidity"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getPrice"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateAPY"
  ): TypedContractMethod<[newAPY: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateLiquidity"
  ): TypedContractMethod<[newLiquidity: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updatePrice"
  ): TypedContractMethod<[newPrice: BigNumberish], [void], "nonpayable">;

  getEvent(
    key: "APYUpdated"
  ): TypedContractEvent<
    APYUpdatedEvent.InputTuple,
    APYUpdatedEvent.OutputTuple,
    APYUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "LiquidityUpdated"
  ): TypedContractEvent<
    LiquidityUpdatedEvent.InputTuple,
    LiquidityUpdatedEvent.OutputTuple,
    LiquidityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OraclePriceUpdated"
  ): TypedContractEvent<
    OraclePriceUpdatedEvent.InputTuple,
    OraclePriceUpdatedEvent.OutputTuple,
    OraclePriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ThresholdCrossed"
  ): TypedContractEvent<
    ThresholdCrossedEvent.InputTuple,
    ThresholdCrossedEvent.OutputTuple,
    ThresholdCrossedEvent.OutputObject
  >;

  filters: {
    "APYUpdated(uint256,uint256)": TypedContractEvent<
      APYUpdatedEvent.InputTuple,
      APYUpdatedEvent.OutputTuple,
      APYUpdatedEvent.OutputObject
    >;
    APYUpdated: TypedContractEvent<
      APYUpdatedEvent.InputTuple,
      APYUpdatedEvent.OutputTuple,
      APYUpdatedEvent.OutputObject
    >;

    "LiquidityUpdated(uint256,uint256)": TypedContractEvent<
      LiquidityUpdatedEvent.InputTuple,
      LiquidityUpdatedEvent.OutputTuple,
      LiquidityUpdatedEvent.OutputObject
    >;
    LiquidityUpdated: TypedContractEvent<
      LiquidityUpdatedEvent.InputTuple,
      LiquidityUpdatedEvent.OutputTuple,
      LiquidityUpdatedEvent.OutputObject
    >;

    "OraclePriceUpdated(uint256,uint256)": TypedContractEvent<
      OraclePriceUpdatedEvent.InputTuple,
      OraclePriceUpdatedEvent.OutputTuple,
      OraclePriceUpdatedEvent.OutputObject
    >;
    OraclePriceUpdated: TypedContractEvent<
      OraclePriceUpdatedEvent.InputTuple,
      OraclePriceUpdatedEvent.OutputTuple,
      OraclePriceUpdatedEvent.OutputObject
    >;

    "ThresholdCrossed(string,uint256,uint256)": TypedContractEvent<
      ThresholdCrossedEvent.InputTuple,
      ThresholdCrossedEvent.OutputTuple,
      ThresholdCrossedEvent.OutputObject
    >;
    ThresholdCrossed: TypedContractEvent<
      ThresholdCrossedEvent.InputTuple,
      ThresholdCrossedEvent.OutputTuple,
      ThresholdCrossedEvent.OutputObject
    >;
  };
}
