/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC165__factory>;
    getContractFactory(
      name: "ISomniaEventHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISomniaEventHandler__factory>;
    getContractFactory(
      name: "ISomniaReactivityPrecompile",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISomniaReactivityPrecompile__factory>;
    getContractFactory(
      name: "SomniaEventHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.SomniaEventHandler__factory>;
    getContractFactory(
      name: "IReactiveOrchestrator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IReactiveOrchestrator__factory>;
    getContractFactory(
      name: "ISource",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ISource__factory>;
    getContractFactory(
      name: "ITarget",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITarget__factory>;
    getContractFactory(
      name: "ReactiveOrchestrator",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReactiveOrchestrator__factory>;
    getContractFactory(
      name: "LiquidityPool",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.LiquidityPool__factory>;
    getContractFactory(
      name: "StakingManager",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.StakingManager__factory>;

    getContractAt(
      name: "IERC165",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC165>;
    getContractAt(
      name: "ISomniaEventHandler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISomniaEventHandler>;
    getContractAt(
      name: "ISomniaReactivityPrecompile",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISomniaReactivityPrecompile>;
    getContractAt(
      name: "SomniaEventHandler",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.SomniaEventHandler>;
    getContractAt(
      name: "IReactiveOrchestrator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IReactiveOrchestrator>;
    getContractAt(
      name: "ISource",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ISource>;
    getContractAt(
      name: "ITarget",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITarget>;
    getContractAt(
      name: "ReactiveOrchestrator",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReactiveOrchestrator>;
    getContractAt(
      name: "LiquidityPool",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.LiquidityPool>;
    getContractAt(
      name: "StakingManager",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.StakingManager>;

    deployContract(
      name: "IERC165",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ISomniaEventHandler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaEventHandler>;
    deployContract(
      name: "ISomniaReactivityPrecompile",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaReactivityPrecompile>;
    deployContract(
      name: "SomniaEventHandler",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SomniaEventHandler>;
    deployContract(
      name: "IReactiveOrchestrator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReactiveOrchestrator>;
    deployContract(
      name: "ISource",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISource>;
    deployContract(
      name: "ITarget",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITarget>;
    deployContract(
      name: "ReactiveOrchestrator",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReactiveOrchestrator>;
    deployContract(
      name: "LiquidityPool",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LiquidityPool>;
    deployContract(
      name: "StakingManager",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakingManager>;

    deployContract(
      name: "IERC165",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC165>;
    deployContract(
      name: "ISomniaEventHandler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaEventHandler>;
    deployContract(
      name: "ISomniaReactivityPrecompile",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISomniaReactivityPrecompile>;
    deployContract(
      name: "SomniaEventHandler",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.SomniaEventHandler>;
    deployContract(
      name: "IReactiveOrchestrator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReactiveOrchestrator>;
    deployContract(
      name: "ISource",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ISource>;
    deployContract(
      name: "ITarget",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITarget>;
    deployContract(
      name: "ReactiveOrchestrator",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReactiveOrchestrator>;
    deployContract(
      name: "LiquidityPool",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.LiquidityPool>;
    deployContract(
      name: "StakingManager",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.StakingManager>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
